name: Deploy CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          ssh vizon.ro "rm -rf /var/www/html/anthala.uk/*"
          scp -r * vizon.ro:/var/www/html/anthala.uk
          ssh vizon.ro "rm -rf /var/www/html/anthala.uk/backend"